server:
  port: 9090

app:
  rate-booking-duration: 120
  default-base-currency: GBP
  default-additional-pip: 1
  forex-rate-api-url: http://localhost:3000
  ip-filter:
    allowed-ip-range: 127.0.0.1
    enabled: false

debug: false

springdoc:
  api-docs:
    path: /api-docs

spring:
  jpa:
    generate-ddl: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: false
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE

#logging:
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} %p %class{36}.%M - %m%n"
#  level:
#    space:
#      gavinklfong: INFO
#    org:
#      springframework:
#        r2dbc: INFO
