# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java Application Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Bump version
        id: version
        uses: anothrNick/github-tag-action@v1 # Don't use @master or @v1 unless you're happy to test the latest version
        env:
          WITH_V: true
          GIT_API_TAGGING: false
          DRY_RUN: true
          DEFAULT_BRANCH: github-action-demo
      - name: output
        run: echo ${{ steps.version.outputs.new_tag }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Update version
        run: mvn versions:set -DnewVersion=${{ steps.version.outputs.new_tag }}
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '**/target/surefire-reports/TEST-*.xml'
          include_passed: true
          detailed_summary: true

      - name: Tag version
        uses: anothrNick/github-tag-action@v1 # Don't use @master or @v1 unless you're happy to test the latest version
        env:
          WITH_V: true
          GIT_API_TAGGING: false
          DRY_RUN: false
          DEFAULT_BRANCH: github-action-demo

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: ${{ github.workspace }}/**/*

  build-image:
    needs: build
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ vars.GITHUB_REPOSITORY }}:${{ needs.build.version.outputs.new_tag }}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: my-artifact
      - name: output variable
        run: echo ${{ env.IMAGE_TAG }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and export to Docker
        uses: docker/build-push-action@v6
        with:
          load: true
          context: .
          file: ${{ github.workspace }}/docker/Dockerfile
          tags: ${{ env.IMAGE_TAG }}
      - name: Test docker image
        run: |
          docker run --rm ${{ env.IMAGE_TAG }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          file: ${{ github.workspace }}/docker/Dockerfile
          tags: ${{ env.IMAGE_TAG }}