name: Simple Workflow

on: 
  workflow_dispatch:

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: step 1
        run: |
          echo "execute job 1 - step 1"
      - name: step 2
        run: |
          echo "execute job 1 - step 2"
  job_2:
    needs: [ job_1 ]
    runs-on: ubuntu-latest
    steps:
      - name: step 1
        run: |
          echo "execute job 2"
  job_3:
    needs: [ job_1 ]
    runs-on: ubuntu-latest
    steps:
      - name: step 1
        run: |
          echo "execute job 3"          
