name: Simple Workflow

on: 
  workflow_dispatch:

jobs:
  job_A:
    runs-on: ubuntu-latest
    steps:
      - name: step A1
        run: |
          echo "execute job A - step 1"
      - name: step A2
        run: |
          echo "execute job A - step 2"
  job_B:
    needs: [ job_A ]
    runs-on: ubuntu-latest
    steps:
      - name: step B1
        run: |
          echo "execute job B"
  job_C:
    needs: [ job_A ]
    runs-on: ubuntu-latest
    steps:
      - name: step C1
        run: |
          echo "execute job C"          
